@echo off
echo Setting the password...
SET PGPASSWORD=12345678
echo Importing states...
psql --username=iastracker -d IASTrackerDB -f estats/estats.sql > nul
echo Importing regions...
psql --username=iastracker -d IASTrackerDB -f regions/regions.sql > nul
echo Importing areas...
psql --username=iastracker -d IASTrackerDB -f areas/areas.sql > nul