SELECT UpdateGeometrySRID('cntr_rg_03m_2014_wgs84','geom',4326);
INSERT INTO "States"("name", "cntr_id", "isActive", "creatorId", "created_at", "updated_at", "geom") SELECT "name_gaul", "cntr_id", FALSE, 1, NOW(), NOW(), "geom" FROM cntr_rg_03m_2014_wgs84 WHERE poli_org_c != 99;
DROP TABLE cntr_rg_03m_2014_wgs84;
SELECT UpdateGeometrySRID('nuts_rg_01m_2013_levl_2_wgs84','geom',4326);
INSERT INTO "regions"("name", "stateId", "isActive", "creatorId", "created_at", "updated_at", "geom") SELECT b."name_asci", (SELECT id FROM "States" WHERE b."cntr_code"="cntr_id"), FALSE, 1, NOW(), NOW(), b."geom" FROM nuts_rg_01m_2013_levl_2_wgs84 b;
DROP TABLE nuts_rg_01m_2013_levl_2_wgs84;
SELECT UpdateGeometrySRID('iastracker_regions_wgs84','geom',4326);
INSERT INTO "Areas"("id", "shapeFileURL", "name", "zIndex", "creatorId", "created_at", "updated_at", "geom") SELECT "iasrid", '', "iasr_name", "iasr_order", 1, NOW(), NOW(), "geom" FROM iastracker_regions_wgs84;
DROP TABLE iastracker_regions_wgs84;
INSERT INTO "RegionAreas"("areaId", "regionId", "created_at", "updated_at") SELECT a.id, r.id, NOW(), NOW() FROM "Areas" a, "regions" r WHERE ST_Intersects(a.geom, r.geom);
INSERT INTO "StateAreas"("areaId", "stateId", "created_at", "updated_at") SELECT a.id, s.id, NOW(), NOW() FROM "Areas" a, "States" s WHERE ST_Intersects(a.geom, s.geom);
UPDATE "States" SET "isActive"=TRUE WHERE "name" IN ('Spain', 'Belgium', 'Mexico');
UPDATE "regions" SET "isActive"=TRUE WHERE "stateId" IN (51, 21, 149);
UPDATE "Areas" SET "shapeFileURL"='shapes/montseny.zip' WHERE id=1;
UPDATE "Areas" SET "shapeFileURL"='shapes/catalunya.zip' WHERE id=0;
UPDATE "Areas" SET "shapeFileURL"='shapes/barcelona.zip' WHERE id=2;
UPDATE "Areas" SET "shapeFileURL"='shapes/bergueda.zip' WHERE id=3;
UPDATE "Areas" SET "shapeFileURL"='shapes/berga.zip' WHERE id=4;
UPDATE "Areas" SET "shapeFileURL"='shapes/belgica.zip' WHERE id=5;
UPDATE "Areas" SET "shapeFileURL"='shapes/mexic.zip' WHERE id=6;
INSERT INTO "ObservationAreas"("observationId", "areaId", "created_at", "updated_at") VALUES(4,4, NOW(), NOW()),(4,3, NOW(), NOW()),(4,0, NOW(), NOW()),(7,3, NOW(), NOW()),(7,0, NOW(), NOW());