@echo off
echo Creating the database...
SET PGPASSWORD=pw150782
psql --username=postgres -f preInstall.sql
echo Migrating...
cd ../web
php artisan migrate
echo Seeding...
php artisan db:seed
cd ../install/
echo Setting the password...
SET PGPASSWORD=12345678
echo Importing states...
psql --username=iastracker -d IASTrackerDB -f shapes/estats.sql > nul
echo Importing regions...
psql --username=iastracker -d IASTrackerDB -f shapes/regions.sql > nul
echo Importing areas...
psql --username=iastracker -d IASTrackerDB -f shapes/areas.sql > nul
echo Post install...
psql --username=iastracker -d IASTrackerDB -f postInstall.sql > nul
echo Ok!